version: '3'

services:
  zookeeper:
    image: zookeeper:3.6
    container_name: zk.local
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka.local
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://172.17.0.1:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zk.local:2181
